name: CI/CD to EKS (Multi-service)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
  NAMESPACE: voting-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    outputs:
      image_tag: ${{ steps.meta.outputs.tag }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tag
        id: meta
        run: echo "tag=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build + push VOTE
      - name: Build & Push vote
        uses: docker/build-push-action@v6
        with:
          context: ./vote
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/vote:${{ steps.meta.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/vote:latest

      # Build + push RESULT
      - name: Build & Push result
        uses: docker/build-push-action@v6
        with:
          context: ./result
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/result:${{ steps.meta.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/result:latest

      # Build + push WORKER
      - name: Build & Push worker
        uses: docker/build-push-action@v6
        with:
          context: ./worker
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/worker:${{ steps.meta.outputs.tag }}
            ${{ secrets.DOCKERHUB_USERNAME }}/worker:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: v1.29.0

      - name: Install eksctl
        run: |
          curl -sLO "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_Linux_amd64.tar.gz"
          tar -xzf eksctl_Linux_amd64.tar.gz
          sudo mv eksctl /usr/local/bin/eksctl

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --region "$AWS_REGION" --name "$CLUSTER_NAME"

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f k8s/ -n $NAMESPACE

      - name: Update images to new tag
        run: |
          TAG="${{ needs.build-and-push.outputs.image_tag }}"
          USER="${{ secrets.DOCKERHUB_USERNAME }}"

          kubectl set image deployment/vote vote=$USER/vote:$TAG -n $NAMESPACE
          kubectl set image deployment/result result=$USER/result:$TAG -n $NAMESPACE
          kubectl set image deployment/worker worker=$USER/worker:$TAG -n $NAMESPACE

      - name: Wait for rollout
        run: |
          kubectl rollout status deployment/vote -n $NAMESPACE --timeout=180s
          kubectl rollout status deployment/result -n $NAMESPACE --timeout=180s
          kubectl rollout status deployment/worker -n $NAMESPACE --timeout=180s

      - name: Show service URLs
        run: |
          kubectl get svc -n $NAMESPACE -o wide
